package main

import (
	"testing"
)

func TestHashAndVerifyPassword(t *testing.T) {
	password := "12345678"

	// Hash the password
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	t.Logf("Generated hash: %s", hash)

	// Verify with correct password
	if !VerifyPassword(password, hash) {
		t.Fatal("VerifyPassword failed with correct password")
	}

	// Verify with wrong password
	if VerifyPassword("wrongpassword", hash) {
		t.Fatal("VerifyPassword succeeded with wrong password")
	}
}

func TestVerifyPasswordWithKnownHash(t *testing.T) {
	// Test with a known hash generated by the fixed code
	password := "12345678"
	hash, err := HashPassword(password)
	if err != nil {
		t.Fatalf("HashPassword failed: %v", err)
	}

	t.Logf("Hash: %s", hash)

	if !VerifyPassword(password, hash) {
		t.Fatal("Verification failed for freshly hashed password")
	}
}

func TestVerifyPasswordInvalidHash(t *testing.T) {
	// Test with malformed hashes
	if VerifyPassword("password", "invalid") {
		t.Fatal("VerifyPassword succeeded with invalid hash format")
	}

	if VerifyPassword("password", "$argon2id$invalid") {
		t.Fatal("VerifyPassword succeeded with incomplete hash")
	}
}
